### GET https://api.ipify.org/

### GET https://http-practice.herokuapp.com/status
###Accept: application/json


###GET https://http-practice.herokuapp.com/wilders
###?language=C

###GET  https://http-practice.herokuapp.com/wilders
###?page=2

###POST https://http-practice.herokuapp.com/wilders
###Content-Type: application/x-www-form-urlencoded

###name=Teddy%20Andria&language=PHP

###POST https://http-practice.herokuapp.com/wilders
###Content-Type: application/json

###{
 ### "name": "Teddy Smith",
###  "language": "PHP"
###}

###GET https://http-practice.herokuapp.com/wilders/1646739

###PUT https://http-practice.herokuapp.com/wilders/1646739
###Content-Type: application/json

###{
   ### "name": "James Bond",
   ### "language": "PHP"
###}

###DELETE https://http-practice.herokuapp.com/wilders/1646739
